import{a as m,i as l,S as y}from"./assets/vendor-29bc32e7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&e(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function e(t){if(t.ep)return;t.ep=!0;const s=i(t);fetch(t.href,s)}})();const p=({webformatURL:o,largeImageURL:r,tags:i,likes:e,views:t,comments:s,downloads:n})=>`
    <li class="gallery-card">
      <a href="${r}" class="gallery-link">
        <img class="gallery-image" src="${o}" alt="${i}" />
      </a>
      <div class="gallery-card-info">
        <p><strong>Likes:</strong> ${e}</p>
        <p><strong>Views:</strong> ${t}</p>
        <p><strong>Comments:</strong> ${s}</p>
        <p><strong>Downloads:</strong> ${n}</p>
      </div>
    </li>
  `;m.defaults.baseURL="https://pixabay.com/api/";const L="45206058-c611c9adec5d897ba1c6c02b0",f=async(o,r)=>{const i={params:{key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}};try{const e=await m.get("",i);if(e&&e.data&&e.data.hits)return e.data;throw new Error("Unexpected response structure")}catch(e){throw console.error("Something went wrong:",e.message||e),e}},w=document.querySelector(".js-search-form"),g=document.querySelector(".js-gallery"),a=document.querySelector(".js-loader"),h=document.querySelector(".js-load-more-btn");let c,d="",u=1;const b=async o=>{if(o.preventDefault(),d=o.target.elements.user_query.value.trim(),o.target.elements.user_query.value="",u=1,d===""){l.error({message:"Please fill in this place",position:"topRight"});return}g.innerHTML="",h.classList.add("is-hidden"),a.classList.remove("is-hidden");try{const{hits:r,totalHits:i}=await f(d,u);if(a.classList.add("is-hidden"),r.length===0){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const e=r.map(p).join("");g.innerHTML=e,c?c.refresh():c=new y(".gallery-link",{captionsData:"alt",captionDelay:250}),i>r.length&&h.classList.remove("is-hidden")}catch(r){l.error({title:"Error",message:`Something went wrong: ${r.message}`,position:"topRight"}),a.classList.add("is-hidden")}},S=async()=>{u+=1,a.classList.remove("is-hidden");try{const{hits:o,totalHits:r}=await f(d,u);a.classList.add("is-hidden");const i=o.map(p).join("");g.insertAdjacentHTML("beforeend",i),c.refresh(),g.children.length>=r&&(h.classList.add("is-hidden"),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const{height:e}=document.querySelector(".gallery-card").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch(o){l.error({title:"Error",message:`Something went wrong: ${o.message}`,position:"topRight"}),a.classList.add("is-hidden")}};w.addEventListener("submit",b);h.addEventListener("click",S);
//# sourceMappingURL=commonHelpers.js.map
